/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agilee;

//import java.awt.BorderLayout;
import DAO.PhanAnhKhachHangDAO;
import DAO.VeDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PhanAnhKhachHang;
import model.Ve;

//import java.awt.Color;
//import java.awt.Font;
//import javax.swing.JFrame;
//import javax.swing.JLabel;
//import javax.swing.JPanel;
//import javax.swing.JScrollPane;
//import javax.swing.JTable;
//import javax.swing.table.DefaultTableCellRenderer;
//import javax.swing.table.JTableHeader;
/**
 *
 * @author admin
 */
public class PhanAnhKH extends javax.swing.JFrame {

    List<Ve> listve = new ArrayList();
    VeDAO veDao = new VeDAO();
    /**
     * Creates new form Login
     */

   List<PhanAnhKhachHang> list = new ArrayList<>();
    PhanAnhKhachHangDAO paDAO = new PhanAnhKhachHangDAO();
    public PhanAnhKH() {
        initComponents();
        setLocationRelativeTo(null);
        loadDataToTable();

//        JTable table;
//        setTitle("JTableHeader");
//          JTableHeader jTableHeader = jTable2.getTableHeader();          
//          
//        
//
//        setTitle("JTableHeader");
//        jTableHeader.setBackground(Color.ORANGE);
//        jTableHeader.setForeground(Color.BLACK); 
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVe = new javax.swing.JButton();
        btnPhong = new javax.swing.JButton();
        btnThietbi = new javax.swing.JButton();
        btnNhanvien = new javax.swing.JButton();
        btnKhachhang = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnPhim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhGia = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNoiDung = new javax.swing.JTextArea();
        txtMaKhachHang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1085, 627));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        btnVe.setBackground(new java.awt.Color(0, 0, 0));
        btnVe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVe.setForeground(new java.awt.Color(255, 255, 255));
        btnVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/390134.png"))); // NOI18N
        btnVe.setText("VÉ");
        btnVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVeMouseExited(evt);
            }
        });
        btnVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeActionPerformed(evt);
            }
        });

        btnPhong.setBackground(new java.awt.Color(0, 0, 0));
        btnPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/phong.png"))); // NOI18N
        btnPhong.setText("PHÒNG");
        btnPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPhongMouseExited(evt);
            }
        });
        btnPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongActionPerformed(evt);
            }
        });

        btnThietbi.setBackground(new java.awt.Color(0, 0, 0));
        btnThietbi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThietbi.setForeground(new java.awt.Color(255, 255, 255));
        btnThietbi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thietbi.png"))); // NOI18N
        btnThietbi.setText("THIẾT BỊ");
        btnThietbi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThietbiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThietbiMouseExited(evt);
            }
        });
        btnThietbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThietbiActionPerformed(evt);
            }
        });

        btnNhanvien.setBackground(new java.awt.Color(0, 0, 0));
        btnNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNhanvien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nhanvien.png"))); // NOI18N
        btnNhanvien.setText("NHÂN VIÊN");
        btnNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanvienMouseExited(evt);
            }
        });
        btnNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanvienActionPerformed(evt);
            }
        });

        btnKhachhang.setBackground(new java.awt.Color(0, 0, 0));
        btnKhachhang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKhachhang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/khach.png"))); // NOI18N
        btnKhachhang.setText("KHÁCH HÀNG");
        btnKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhachhangMouseExited(evt);
            }
        });
        btnKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachhangActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("QUẢN LÝ KHÁCH HÀNG");

        btnPhim.setBackground(new java.awt.Color(0, 0, 0));
        btnPhim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPhim.setForeground(new java.awt.Color(255, 255, 255));
        btnPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/a2.png"))); // NOI18N
        btnPhim.setText("PHIM");
        btnPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPhimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPhimMouseExited(evt);
            }
        });
        btnPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPhim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKhachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVe, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThietbi, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addComponent(btnPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnVe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnThietbi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Mã Khách Hàng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Tên Khách Hàng");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 130, -1));

        txtTenKhachHang.setBackground(new java.awt.Color(0, 153, 0));
        getContentPane().add(txtTenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 140, -1));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        getContentPane().add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Cre: Dr. Stone");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 80, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 204, 255));
        jLabel12.setText("Tên Tài Khoản: user1");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Nội Dung");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        tblDanhGia.setBackground(new java.awt.Color(255, 0, 255));
        tblDanhGia.setForeground(new java.awt.Color(255, 255, 255));
        tblDanhGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Khách Hàng", "Tên Khách Hàng", "Nội dung"
            }
        ));
        tblDanhGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhGia);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 870, 370));

        txtNoiDung.setBackground(new java.awt.Color(0, 153, 0));
        txtNoiDung.setColumns(20);
        txtNoiDung.setRows(5);
        jScrollPane2.setViewportView(txtNoiDung);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        txtMaKhachHang.setBackground(new java.awt.Color(0, 153, 0));
        getContentPane().add(txtMaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 140, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/—Pngtree—geometric purple background with modern_1243070.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1090, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanvienActionPerformed
        Nhanvien();
    }//GEN-LAST:event_btnNhanvienActionPerformed

    public void setColor(JButton p) {
        p.setBackground(new Color(204, 255, 204));
        p.setForeground(new Color(0, 0, 0));
    }

    public void resetColor(JButton p) {
        p.setBackground(new Color(0, 0, 0));
        p.setForeground(new Color(255, 255, 255));
    }

    public void setColor1(JButton p) {
        p.setBackground(new Color(255, 153, 0));
        p.setForeground(new Color(255, 255, 255));
    }

    public void resetColor1(JButton p) {
        p.setBackground(new Color(153, 153, 225));
        p.setForeground(new Color(0, 0, 0));
    }


    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here: 
    }//GEN-LAST:event_jPanel1MouseEntered

    private void btnPhimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhimMouseExited
        // TODO add your handling code here:
        resetColor(btnPhim);
    }//GEN-LAST:event_btnPhimMouseExited

    private void btnPhimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhimMouseEntered
        // TODO add your handling code here:
        setColor(btnPhim);
    }//GEN-LAST:event_btnPhimMouseEntered

    private void btnVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeMouseEntered
        // TODO add your handling code here:
        setColor(btnVe);
    }//GEN-LAST:event_btnVeMouseEntered

    private void btnVeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeMouseExited
        // TODO add your handling code here:
        resetColor(btnVe);
    }//GEN-LAST:event_btnVeMouseExited

    private void btnPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseEntered
        // TODO add your handling code here:
        setColor(btnPhong);
    }//GEN-LAST:event_btnPhongMouseEntered

    private void btnPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseExited
        // TODO add your handling code here:
        resetColor(btnPhong);
    }//GEN-LAST:event_btnPhongMouseExited

    private void btnThietbiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThietbiMouseEntered
        // TODO add your handling code here:
        setColor(btnThietbi);
    }//GEN-LAST:event_btnThietbiMouseEntered

    private void btnThietbiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThietbiMouseExited
        // TODO add your handling code here:
        resetColor(btnThietbi);
    }//GEN-LAST:event_btnThietbiMouseExited

    private void btnNhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanvienMouseEntered
        // TODO add your handling code here:
        setColor(btnNhanvien);
    }//GEN-LAST:event_btnNhanvienMouseEntered

    private void btnNhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanvienMouseExited
        // TODO add your handling code here:
        resetColor(btnNhanvien);
    }//GEN-LAST:event_btnNhanvienMouseExited

    private void btnKhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachhangMouseEntered
        // TODO add your handling code here:
        setColor(btnKhachhang);
    }//GEN-LAST:event_btnKhachhangMouseEntered

    private void btnKhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachhangMouseExited
        // TODO add your handling code here:
        resetColor(btnKhachhang);
    }//GEN-LAST:event_btnKhachhangMouseExited

    private void btnPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhimActionPerformed
        Phim();
    }//GEN-LAST:event_btnPhimActionPerformed

    private void btnVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeActionPerformed
        Ve();
    }//GEN-LAST:event_btnVeActionPerformed

    private void btnPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongActionPerformed
        Phong();
    }//GEN-LAST:event_btnPhongActionPerformed

    private void btnThietbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThietbiActionPerformed
        Thietbi();
    }//GEN-LAST:event_btnThietbiActionPerformed

    private void btnKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKhachhangActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        Find();
    }//GEN-LAST:event_btnFindActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Add();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblDanhGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhGiaMouseClicked
        fillToForm(tblDanhGia.getSelectedRow());
    }//GEN-LAST:event_tblDanhGiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhanAnhKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhanAnhKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhanAnhKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhanAnhKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhanAnhKH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnKhachhang;
    private javax.swing.JButton btnNhanvien;
    private javax.swing.JButton btnPhim;
    private javax.swing.JButton btnPhong;
    private javax.swing.JButton btnThietbi;
    private javax.swing.JButton btnVe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDanhGia;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextArea txtNoiDung;
    private javax.swing.JTextField txtTenKhachHang;
    // End of variables declaration//GEN-END:variables

    public void loadDataToTable() {
        list = paDAO.getAll();
        listve = veDao.getAll();
        String[] columnNames = {"Mã khách hàng", "Tên khách hàng", "Nội Dung"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        for (PhanAnhKhachHang pa : list) {
            model.addRow(new Object[]{pa.getMaKH(), pa.getTenKh(), pa.getNoiDung()});
        }
        tblDanhGia.setModel(model);
    }

    public void fillToForm(int index) {
        PhanAnhKhachHang pakh = list.get(index);
        txtMaKhachHang.setText(pakh.getMaKH());
        txtTenKhachHang.setText(pakh.getTenKh());
        txtNoiDung.setText(pakh.getNoiDung());
        tblDanhGia.setRowSelectionInterval(index, index);
    }

    public boolean checkma() {
        for (Ve ve : listve) {
            if (txtMaKhachHang.getText().equals(ve.getMakhachhang())) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(null, "Khách hàng chưa xem phim tại rạp");
        return false;
    }

    public boolean checkNull() {
        if (txtMaKhachHang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã khách hàng");
            txtMaKhachHang.requestFocus();
            return false;
        }
        if (checkma()==false) {
            return false;
        }
        if (txtTenKhachHang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên khách hàng");
            txtTenKhachHang.requestFocus();
            return false;
        }
        if (txtNoiDung.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập nội dung");
            txtNoiDung.requestFocus();
            return false;
        }
        return true;
    }

    public void Add() {
        if (checkNull()) {
            PhanAnhKhachHang pa = new PhanAnhKhachHang();
            pa.setMaKH(txtMaKhachHang.getText());
            pa.setTenKh(txtTenKhachHang.getText());
            pa.setNoiDung(txtNoiDung.getText());
            int rs = PhanAnhKhachHangDAO.insert(pa);
            if (rs > 0) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                loadDataToTable();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        }
    }

    public void Find() {
        if (txtMaKhachHang.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã khách hàng để tìm");
            txtMaKhachHang.requestFocus();
            return;
        }
        for (PhanAnhKhachHang pakh : list) {
            if (txtMaKhachHang.getText().equals(pakh.getMaKH())) {
                txtTenKhachHang.setText(pakh.getTenKh());
                txtNoiDung.setText(pakh.getNoiDung());
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "Không tìm thấy khách hàng ");
    }

    public void Nhanvien() {
        QuanLyNhanVien nvi = new QuanLyNhanVien();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        nvi.setVisible(true);
        this.dispose();
        return;

    }

    public void Ve() {
        QuanLyVe ve = new QuanLyVe();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        ve.setVisible(true);
        this.dispose();
        return;

    }

    public void Phong() {
        QuanLyPhong phong = new QuanLyPhong();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        phong.setVisible(true);
        this.dispose();
        return;

    }

    public void Thietbi() {
        QuanLyThietBi tbi = new QuanLyThietBi();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        tbi.setVisible(true);
        this.dispose();
        return;

    }

    public void Khachhang() {
        PhanAnhKH khachhang = new PhanAnhKH();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        khachhang.setVisible(true);
        this.dispose();
        return;

    }

    public void Phim() {
        QuanLyPhim phim = new QuanLyPhim();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        phim.setVisible(true);
        this.dispose();
        return;

    }

}
