/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agilee;

//import java.awt.BorderLayout;
import DAO.GheDAO;
import DAO.MoviesDAO;
import DAO.NhanVienDao;
import DAO.PhongDao;
import DAO.VeDAO;
import java.awt.Color;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ghe;
import model.Movies;
import model.NhanVien;
import model.Phong;
import model.Ve;

//import java.awt.Color;
//import java.awt.Font;
//import javax.swing.JFrame;
//import javax.swing.JLabel;
//import javax.swing.JPanel;
//import javax.swing.JScrollPane;
//import javax.swing.JTable;
//import javax.swing.table.DefaultTableCellRenderer;
//import javax.swing.table.JTableHeader;
/**
 *
 * @author admin
 */
public class QuanLyVe extends javax.swing.JFrame {

    List<Ve> list = new ArrayList<>();
    VeDAO vDao = new VeDAO();
    List<Movies> listmovies = new ArrayList<>();
    MoviesDAO mvDao = new MoviesDAO();
    List<NhanVien> listnv = new ArrayList<>();
    NhanVienDao nvDao = new NhanVienDao();
    List<Phong> listP = new ArrayList<>();
    PhongDao PhongDao = new PhongDao();
    List<Ghe> listghe = new ArrayList<>();
    GheDAO gheDao = new GheDAO();
    int bam = 0;

    /**
     * Creates new form Login
     */
    public QuanLyVe() {
        initComponents();
        setLocationRelativeTo(null);
        loadDataToTableVe();
        TXTTONGTIEN.setEnabled(false);
        TXTTENpHIM.setEnabled(false);
        TXTHANG.setEnabled(false);
        TXTCOT.setEnabled(false);

//        JTable table;
//        setTitle("JTableHeader");
//          JTableHeader jTableHeader = jTable2.getTableHeader();          
//          
//        
//
//        setTitle("JTableHeader");
//        jTableHeader.setBackground(Color.ORANGE);
//        jTableHeader.setForeground(Color.BLACK); 
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnVe = new javax.swing.JButton();
        btnPhong = new javax.swing.JButton();
        btnThietbi = new javax.swing.JButton();
        btnNhanvien = new javax.swing.JButton();
        btnKhachhang = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnPhim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXTMANV = new javax.swing.JTextField();
        txtMaHD = new javax.swing.JTextField();
        txtMAKH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnTinh = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        TXTPHONG = new javax.swing.JTextField();
        TXTHANG = new javax.swing.JTextField();
        TXTCOT = new javax.swing.JTextField();
        TXTNGAYBAN = new javax.swing.JTextField();
        TXTTONGTIEN = new javax.swing.JTextField();
        TXTMAPHIM = new javax.swing.JTextField();
        TXTTENpHIM = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        RDO79 = new javax.swing.JRadioButton();
        RDO911 = new javax.swing.JRadioButton();
        RDO1113 = new javax.swing.JRadioButton();
        RDO1517 = new javax.swing.JRadioButton();
        RDO1315 = new javax.swing.JRadioButton();
        RDO1719 = new javax.swing.JRadioButton();
        RDO1921 = new javax.swing.JRadioButton();
        TXTMAGHE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        TXTsOLUONGVE = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        RDO2123 = new javax.swing.JRadioButton();
        BTNXUATHOADON2 = new javax.swing.JButton();
        BTNNEW1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1085, 627));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        btnVe.setBackground(new java.awt.Color(0, 0, 0));
        btnVe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVe.setForeground(new java.awt.Color(255, 255, 255));
        btnVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/390134.png"))); // NOI18N
        btnVe.setText("VÉ");
        btnVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVeMouseExited(evt);
            }
        });
        btnVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeActionPerformed(evt);
            }
        });

        btnPhong.setBackground(new java.awt.Color(0, 0, 0));
        btnPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/phong.png"))); // NOI18N
        btnPhong.setText("PHÒNG");
        btnPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPhongMouseExited(evt);
            }
        });
        btnPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongActionPerformed(evt);
            }
        });

        btnThietbi.setBackground(new java.awt.Color(0, 0, 0));
        btnThietbi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThietbi.setForeground(new java.awt.Color(255, 255, 255));
        btnThietbi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thietbi.png"))); // NOI18N
        btnThietbi.setText("THIẾT BỊ");
        btnThietbi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThietbiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThietbiMouseExited(evt);
            }
        });
        btnThietbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThietbiActionPerformed(evt);
            }
        });

        btnNhanvien.setBackground(new java.awt.Color(0, 0, 0));
        btnNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNhanvien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nhanvien.png"))); // NOI18N
        btnNhanvien.setText("NHÂN VIÊN");
        btnNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanvienMouseExited(evt);
            }
        });
        btnNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanvienActionPerformed(evt);
            }
        });

        btnKhachhang.setBackground(new java.awt.Color(0, 0, 0));
        btnKhachhang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKhachhang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/khach.png"))); // NOI18N
        btnKhachhang.setText("KHÁCH HÀNG");
        btnKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhachhangMouseExited(evt);
            }
        });
        btnKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachhangActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("QUẢN LÍ VÉ");

        btnPhim.setBackground(new java.awt.Color(0, 0, 0));
        btnPhim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPhim.setForeground(new java.awt.Color(255, 255, 255));
        btnPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/a2.png"))); // NOI18N
        btnPhim.setText("PHIM");
        btnPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPhimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPhimMouseExited(evt);
            }
        });
        btnPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVe, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThietbi, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPhim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKhachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addComponent(btnPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnVe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnThietbi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Mã Hóa Đơn");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 90, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Mã Khách Hàng");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Mã Nhân Viên");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 90, -1));

        TXTMANV.setBackground(new java.awt.Color(0, 153, 0));
        TXTMANV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTMANV.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TXTMANV, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 261, -1));

        txtMaHD.setBackground(new java.awt.Color(0, 153, 0));
        txtMaHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMaHD.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 261, -1));

        txtMAKH.setBackground(new java.awt.Color(0, 153, 0));
        txtMAKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMAKH.setForeground(new java.awt.Color(255, 255, 255));
        txtMAKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMAKHActionPerformed(evt);
            }
        });
        getContentPane().add(txtMAKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 261, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Cre: Dr. Stone");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, 80, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 204, 255));
        jLabel12.setText("Tên Tài Khoản: user1");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 150, 20));

        btnTinh.setBackground(new java.awt.Color(153, 153, 255));
        btnTinh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-coin-20.png"))); // NOI18N
        btnTinh.setText("Tính");
        btnTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTinhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTinhMouseExited(evt);
            }
        });
        btnTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhActionPerformed(evt);
            }
        });
        getContentPane().add(btnTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 90, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 153, 51));
        jLabel30.setText("Mã Phim");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 153, 51));
        jLabel31.setText("Tên Phim");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 153, 51));
        jLabel32.setText("Số Lượng vé");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 153, 51));
        jLabel33.setText("Mã Ghế");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 153, 0));
        jLabel34.setText("Cột");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 153, 51));
        jLabel35.setText("Ngày Bán");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 153, 51));
        jLabel36.setText("Tổng Tiền");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, -1, -1));

        TXTPHONG.setBackground(new java.awt.Color(0, 153, 0));
        TXTPHONG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTPHONG.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TXTPHONG, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 264, -1));

        TXTHANG.setBackground(new java.awt.Color(0, 153, 0));
        TXTHANG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTHANG.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TXTHANG, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 33, -1));

        TXTCOT.setBackground(new java.awt.Color(0, 153, 0));
        TXTCOT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTCOT.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TXTCOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 35, -1));

        TXTNGAYBAN.setBackground(new java.awt.Color(0, 153, 0));
        TXTNGAYBAN.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TXTNGAYBAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 261, -1));

        TXTTONGTIEN.setBackground(new java.awt.Color(0, 153, 0));
        TXTTONGTIEN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTTONGTIEN.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TXTTONGTIEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 160, -1));

        TXTMAPHIM.setBackground(new java.awt.Color(0, 153, 0));
        TXTMAPHIM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTMAPHIM.setForeground(new java.awt.Color(255, 255, 255));
        TXTMAPHIM.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TXTMAPHIMCaretUpdate(evt);
            }
        });
        TXTMAPHIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTMAPHIMActionPerformed(evt);
            }
        });
        getContentPane().add(TXTMAPHIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 264, -1));

        TXTTENpHIM.setBackground(new java.awt.Color(0, 153, 0));
        TXTTENpHIM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTTENpHIM.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TXTTENpHIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 264, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 153, 51));
        jLabel37.setText("Hàng");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 153, 51));
        jLabel38.setText("Giờ Chiếu");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        buttonGroup1.add(RDO79);
        RDO79.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RDO79.setForeground(new java.awt.Color(255, 255, 255));
        RDO79.setText("7:45-9:45");
        getContentPane().add(RDO79, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        buttonGroup1.add(RDO911);
        RDO911.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RDO911.setForeground(new java.awt.Color(255, 255, 255));
        RDO911.setText("9:45-11:45");
        getContentPane().add(RDO911, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        buttonGroup1.add(RDO1113);
        RDO1113.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RDO1113.setForeground(new java.awt.Color(255, 255, 255));
        RDO1113.setText("11:45-13:45");
        getContentPane().add(RDO1113, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        buttonGroup1.add(RDO1517);
        RDO1517.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RDO1517.setForeground(new java.awt.Color(255, 255, 255));
        RDO1517.setText("15:45-17:45");
        RDO1517.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDO1517ActionPerformed(evt);
            }
        });
        getContentPane().add(RDO1517, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        buttonGroup1.add(RDO1315);
        RDO1315.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RDO1315.setForeground(new java.awt.Color(255, 255, 255));
        RDO1315.setText("13:45-15:45");
        getContentPane().add(RDO1315, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        buttonGroup1.add(RDO1719);
        RDO1719.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RDO1719.setForeground(new java.awt.Color(255, 255, 255));
        RDO1719.setText("17:45-19:45");
        getContentPane().add(RDO1719, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        buttonGroup1.add(RDO1921);
        RDO1921.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RDO1921.setForeground(new java.awt.Color(255, 255, 255));
        RDO1921.setText("19:45-21:45");
        getContentPane().add(RDO1921, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        TXTMAGHE.setBackground(new java.awt.Color(0, 153, 0));
        TXTMAGHE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTMAGHE.setForeground(new java.awt.Color(255, 255, 255));
        TXTMAGHE.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TXTMAGHECaretUpdate(evt);
            }
        });
        getContentPane().add(TXTMAGHE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 90, -1));

        tblHoaDon.setBackground(new java.awt.Color(255, 0, 255));
        tblHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Hóa Đơn"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 240, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 153, 51));
        jLabel39.setText("Phòng");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        TXTsOLUONGVE.setBackground(new java.awt.Color(0, 153, 0));
        TXTsOLUONGVE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXTsOLUONGVE.setForeground(new java.awt.Color(255, 255, 255));
        TXTsOLUONGVE.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TXTsOLUONGVECaretUpdate(evt);
            }
        });
        getContentPane().add(TXTsOLUONGVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 264, -1));

        jTextField13.setBackground(new java.awt.Color(0, 153, 0));
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 264, -1));

        buttonGroup1.add(RDO2123);
        RDO2123.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RDO2123.setForeground(new java.awt.Color(255, 255, 255));
        RDO2123.setText("21:45-23:45");
        getContentPane().add(RDO2123, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        BTNXUATHOADON2.setBackground(new java.awt.Color(153, 153, 255));
        BTNXUATHOADON2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNXUATHOADON2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thue.png"))); // NOI18N
        BTNXUATHOADON2.setText("Xuất Hóa Đơn");
        BTNXUATHOADON2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTNXUATHOADON2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTNXUATHOADON2MouseExited(evt);
            }
        });
        BTNXUATHOADON2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNXUATHOADON2ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNXUATHOADON2, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 540, 180, 40));

        BTNNEW1.setBackground(new java.awt.Color(153, 153, 255));
        BTNNEW1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BTNNEW1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        BTNNEW1.setText("NEW");
        BTNNEW1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BTNNEW1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BTNNEW1MouseExited(evt);
            }
        });
        BTNNEW1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNEW1ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNNEW1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/—Pngtree—geometric purple background with modern_1243070.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMAKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMAKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMAKHActionPerformed

    private void btnNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanvienActionPerformed
        Nhanvien();
    }//GEN-LAST:event_btnNhanvienActionPerformed

    public void setColor(JButton p) {
        p.setBackground(new Color(204, 255, 204));
        p.setForeground(new Color(0, 0, 0));
    }

    public void resetColor(JButton p) {
        p.setBackground(new Color(0, 0, 0));
        p.setForeground(new Color(255, 255, 255));
    }

    public void setColor1(JButton p) {
        p.setBackground(new Color(255, 153, 0));
        p.setForeground(new Color(255, 255, 255));
    }

    public void resetColor1(JButton p) {
        p.setBackground(new Color(153, 153, 225));
        p.setForeground(new Color(0, 0, 0));
    }


    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here: 
    }//GEN-LAST:event_jPanel1MouseEntered

    private void btnPhimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhimMouseExited
        // TODO add your handling code here:
        resetColor(btnPhim);
    }//GEN-LAST:event_btnPhimMouseExited

    private void btnPhimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhimMouseEntered
        // TODO add your handling code here:
        setColor(btnPhim);
    }//GEN-LAST:event_btnPhimMouseEntered

    private void btnVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeMouseEntered
        // TODO add your handling code here:
        setColor(btnVe);
    }//GEN-LAST:event_btnVeMouseEntered

    private void btnVeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeMouseExited
        // TODO add your handling code here:
        resetColor(btnVe);
    }//GEN-LAST:event_btnVeMouseExited

    private void btnPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseEntered
        // TODO add your handling code here:
        setColor(btnPhong);
    }//GEN-LAST:event_btnPhongMouseEntered

    private void btnPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseExited
        // TODO add your handling code here:
        resetColor(btnPhong);
    }//GEN-LAST:event_btnPhongMouseExited

    private void btnThietbiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThietbiMouseEntered
        // TODO add your handling code here:
        setColor(btnThietbi);
    }//GEN-LAST:event_btnThietbiMouseEntered

    private void btnThietbiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThietbiMouseExited
        // TODO add your handling code here:
        resetColor(btnThietbi);
    }//GEN-LAST:event_btnThietbiMouseExited

    private void btnNhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanvienMouseEntered
        // TODO add your handling code here:
        setColor(btnNhanvien);
    }//GEN-LAST:event_btnNhanvienMouseEntered

    private void btnNhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanvienMouseExited
        // TODO add your handling code here:
        resetColor(btnNhanvien);
    }//GEN-LAST:event_btnNhanvienMouseExited

    private void btnKhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachhangMouseEntered
        // TODO add your handling code here:
        setColor(btnKhachhang);
    }//GEN-LAST:event_btnKhachhangMouseEntered

    private void btnKhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachhangMouseExited
        // TODO add your handling code here:
        resetColor(btnKhachhang);
    }//GEN-LAST:event_btnKhachhangMouseExited

    private void btnTinhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTinhMouseEntered
        // TODO add your handling code here:
        setColor1(btnTinh);
    }//GEN-LAST:event_btnTinhMouseEntered

    private void btnTinhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTinhMouseExited
        // TODO add your handling code here:
        resetColor1(btnTinh);
    }//GEN-LAST:event_btnTinhMouseExited

    private void btnPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhimActionPerformed
        Phim();
    }//GEN-LAST:event_btnPhimActionPerformed

    private void btnVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeActionPerformed

    }//GEN-LAST:event_btnVeActionPerformed

    private void btnPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongActionPerformed
        Phong();
    }//GEN-LAST:event_btnPhongActionPerformed

    private void btnThietbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThietbiActionPerformed
        Thietbi();
    }//GEN-LAST:event_btnThietbiActionPerformed

    private void btnKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachhangActionPerformed
        Khachhang();
    }//GEN-LAST:event_btnKhachhangActionPerformed

    private void TXTMAPHIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTMAPHIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTMAPHIMActionPerformed

    private void RDO1517ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDO1517ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDO1517ActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        fillToFrom();
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void BTNXUATHOADON2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNXUATHOADON2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNXUATHOADON2MouseEntered

    private void BTNXUATHOADON2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNXUATHOADON2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNXUATHOADON2MouseExited

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        Tinh();
    }//GEN-LAST:event_btnTinhActionPerformed

    private void BTNNEW1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNNEW1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNNEW1MouseEntered

    private void BTNNEW1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNNEW1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNNEW1MouseExited

    private void BTNNEW1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNEW1ActionPerformed
        newFrom();
    }//GEN-LAST:event_BTNNEW1ActionPerformed

    private void BTNXUATHOADON2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNXUATHOADON2ActionPerformed
        if (checkfrom()) {
            XuatHoaDon();
            newFrom();
        }

    }//GEN-LAST:event_BTNXUATHOADON2ActionPerformed

    private void TXTMAPHIMCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TXTMAPHIMCaretUpdate
        Tenphim();
    }//GEN-LAST:event_TXTMAPHIMCaretUpdate

    private void TXTMAGHECaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TXTMAGHECaretUpdate
        hangcot();
    }//GEN-LAST:event_TXTMAGHECaretUpdate

    private void TXTsOLUONGVECaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TXTsOLUONGVECaretUpdate

    }//GEN-LAST:event_TXTsOLUONGVECaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyVe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyVe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNNEW1;
    private javax.swing.JButton BTNXUATHOADON2;
    private javax.swing.JRadioButton RDO1113;
    private javax.swing.JRadioButton RDO1315;
    private javax.swing.JRadioButton RDO1517;
    private javax.swing.JRadioButton RDO1719;
    private javax.swing.JRadioButton RDO1921;
    private javax.swing.JRadioButton RDO2123;
    private javax.swing.JRadioButton RDO79;
    private javax.swing.JRadioButton RDO911;
    private javax.swing.JTextField TXTCOT;
    private javax.swing.JTextField TXTHANG;
    private javax.swing.JTextField TXTMAGHE;
    private javax.swing.JTextField TXTMANV;
    private javax.swing.JTextField TXTMAPHIM;
    private javax.swing.JTextField TXTNGAYBAN;
    private javax.swing.JTextField TXTPHONG;
    private javax.swing.JTextField TXTTENpHIM;
    private javax.swing.JTextField TXTTONGTIEN;
    private javax.swing.JTextField TXTsOLUONGVE;
    private javax.swing.JButton btnKhachhang;
    private javax.swing.JButton btnNhanvien;
    private javax.swing.JButton btnPhim;
    private javax.swing.JButton btnPhong;
    private javax.swing.JButton btnThietbi;
    private javax.swing.JButton btnTinh;
    private javax.swing.JButton btnVe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtMAKH;
    private javax.swing.JTextField txtMaHD;
    // End of variables declaration//GEN-END:variables

    public void loadDataToTableVe() {
        list = VeDAO.getAll();
        listmovies = mvDao.getAll();
        listnv = nvDao.getAll();
        listP = PhongDao.getAll();
        listghe = gheDao.getAll();
        String[] columnNames = {"Mã Hóa Đơn"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        for (Ve v : list) {
            model.addRow(new Object[]{v.getMahoadon()});
        }
        tblHoaDon.setModel(model);
    }

    public void fillToFrom() {
        int index = tblHoaDon.getSelectedRow();
        Ve v = list.get(index);
        txtMaHD.setText(v.getMahoadon());
        txtMAKH.setText(v.getMakhachhang());
        TXTMANV.setText(v.getManv());
        TXTMAPHIM.setText(v.getMaphim());
        TXTTENpHIM.setText(v.getTenphim());
        TXTsOLUONGVE.setText(String.valueOf(v.getSove()));
        if (v.getSuatchieu().equals("7:45-9:45")) {
            RDO79.setSelected(true);
        } else if (v.getSuatchieu().equals("9:45-11:45")) {
            RDO911.setSelected(true);
        } else if (v.getSuatchieu().equals("7:11:45-13:45")) {
            RDO1113.setSelected(true);
        } else if (v.getSuatchieu().equals("13:45-15:45")) {
            RDO1315.setSelected(true);
        } else if (v.getSuatchieu().equals("15:45-17:45")) {
            RDO1517.setSelected(true);
        } else if (v.getSuatchieu().equals("17:45-1945")) {
            RDO1719.setSelected(true);
        } else if (v.getSuatchieu().equals("19:45-21:45")) {
            RDO1921.setSelected(true);
        } else if (v.getSuatchieu().equals("21:45-23:45")) {
            RDO2123.setSelected(true);
        }

        TXTPHONG.setText(v.getPhong());
        TXTMAGHE.setText(v.getMaghe());
        TXTHANG.setText(v.getSohang());
        TXTCOT.setText(v.getSocot());
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String rDate = df.format(v.getNgaymua());
        TXTNGAYBAN.setText(rDate);
        TXTTONGTIEN.setText(String.valueOf(v.getTongtien()));

    }

    public void newFrom() {
        txtMaHD.setText("");
        txtMAKH.setText("");
        TXTMANV.setText("");
        TXTMAPHIM.setText("");
        TXTTENpHIM.setText("");
        TXTsOLUONGVE.setText("");
        buttonGroup1.clearSelection();
        TXTPHONG.setText("");
        TXTMAGHE.setText("");
        TXTHANG.setText("");
        TXTCOT.setText("");
        TXTNGAYBAN.setText("");
        TXTTONGTIEN.setText("");
    }

    public void XuatHoaDon() {

        Ve v = new Ve();
        v.setMahoadon(txtMaHD.getText());
        v.setMakhachhang(txtMAKH.getText());
        v.setManv(TXTMANV.getText());
        v.setMaphim(TXTMAPHIM.getText());
        v.setTenphim(TXTTENpHIM.getText());
        v.setSove(Integer.parseInt(TXTsOLUONGVE.getText()));
        if (RDO79.isSelected()) {
            v.setSuatchieu("7:45-9:45");
        } else if (RDO911.isSelected()) {
            v.setSuatchieu("9:45-11:45");
        } else if (RDO1113.isSelected()) {
            v.setSuatchieu("11:45-13:45");
        } else if (RDO1315.isSelected()) {
            v.setSuatchieu("13:45-15:45");
        } else if (RDO1517.isSelected()) {
            v.setSuatchieu("15:45-17:45");
        } else if (RDO1719.isSelected()) {
            v.setSuatchieu("17:45-19:45");
        } else if (RDO1921.isSelected()) {
            v.setSuatchieu("19:45-21:45");
        } else if (RDO2123.isSelected()) {
            v.setSuatchieu("21:45-23:45");
        }
        v.setPhong(TXTPHONG.getText());
        v.setMaghe(TXTMAGHE.getText());
        v.setSohang(TXTHANG.getText());
        v.setSocot(TXTCOT.getText());
        try {
            SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
            Date ngayVaoLamDate = df.parse(TXTNGAYBAN.getText());
            v.setNgaymua(new java.sql.Date(ngayVaoLamDate.getTime()));
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng định dạng (Ngày - Tháng - Năm)");
            return;
        }

        v.setTongtien(Integer.parseInt(TXTTONGTIEN.getText()));
        int rs = VeDAO.insert(v);
        loadDataToTableVe();
        if (rs > 0) {
            JOptionPane.showMessageDialog(null, "Xuất Hóa Đơn Thành Công");

        } else {
            JOptionPane.showMessageDialog(null, "Xuất Hóa Đơn Thất Bại");
        }
    }

    public void Tinh() {
        listmovies = mvDao.getAll();
        int TongTien = 0;
        int tien = 0;
        int sove = Integer.parseInt(TXTsOLUONGVE.getText());
        for (Movies movies : listmovies) {
            if (TXTMAPHIM.getText().equals(movies.getMaPhim())) {
                tien = Integer.parseInt(movies.getGiaPhim());
            }
        }
        TongTien = tien * sove;
        TXTTONGTIEN.setText(String.valueOf(TongTien));
    }

    public boolean checkfrom() {

        if (txtMaHD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã hóa đơn");
            return false;
        }
        for (Ve ve : list) {
            if (txtMaHD.getText().equals(ve.getMahoadon())) {
                JOptionPane.showMessageDialog(null, "Mã hóa đơn đã tồn tại");
                return false;
            }
        }
        if (txtMAKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã khách hàng");
            return false;
        }
        if (TXTMANV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã nhân viên");
            return false;
        }

        if (checkmanv() == false) {
            return false;
        }
        if (TXTMAPHIM.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã phim");
            return false;
        }
        if (TXTTENpHIM.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên phim");
            return false;
        }

        if (checkmaPhim() == false) {
            return false;
        }
        if (TXTsOLUONGVE.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập số vé phim");
            return false;
        }
        try {
            int ve = Integer.parseInt(TXTsOLUONGVE.getText());
            if (ve < 1) {
                JOptionPane.showMessageDialog(null, "Bạn phải mua ít nhất một vé");
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Vé phải là số");
            return false;
        }
        boolean suatChieu = RDO79.isSelected() || RDO911.isSelected() || RDO1113.isSelected() || RDO1315.isSelected() || RDO1517.isSelected() || RDO1719.isSelected() || RDO1921.isSelected() || RDO2123.isSelected();
        if (suatChieu == false) {
            JOptionPane.showMessageDialog(null, "Hãy chọn xuất chiếu");
        }
        if (TXTPHONG.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã phòng");
            return false;
        }

        if (checkPhong() == false) {
            return false;
        }
        if (TXTMAGHE.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã ghế");
            return false;
        }

        if (checkghe() == false) {
            return false;
        }
        if (checkghe2() == false) {
            return false;
        }

        if (TXTNGAYBAN.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập ngày bán vé");
            return false;
        }
        return true;
    }

    public boolean checkmanv() {
        listmovies = mvDao.getAll();
        for (NhanVien nv : listnv) {
            if (TXTMANV.getText().equals(nv.getMaNV())) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(null, "Mã nhân viên không tồn tại");
        return false;
    }

    public boolean checkmaPhim() {
        listmovies = mvDao.getAll();
        for (Movies movies : listmovies) {
            if (TXTMAPHIM.getText().equals(movies.getMaPhim())) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(null, "Mã Phim không tồn tại");
        return false;
    }

    public boolean checkPhong() {
        for (Phong phong : listP) {
            if (TXTPHONG.getText().equals(phong.getMa())) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(null, "Mã Phòng không tồn tại");
        return false;
    }

    public boolean checkghe() {
        for (Ghe ghe : listghe) {
            if (TXTMAGHE.getText().equals(ghe.getMaghe())) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(null, "Mã ghế không tồn tại");
        return false;
    }

    public boolean checkghe2() {
        for (Ve v : list) {
            if (TXTMAGHE.getText().equals(v.getMaghe())) {
                JOptionPane.showMessageDialog(null, "Ghế đã được đặt");
                return false;
            }
        }

        return true;
    }

    public void Tenphim() {
        for (Movies movies : listmovies) {
            if (TXTMAPHIM.getText().equals(movies.getMaPhim())) {
                TXTTENpHIM.setText(movies.getTenPhim());
                return;
            }
        }
        TXTTENpHIM.setText("");
    }

    public void hangcot() {
        for (Ghe ghe : listghe) {
            if (TXTMAGHE.getText().equals(ghe.getMaghe())) {
                TXTHANG.setText(ghe.getHang());
                TXTCOT.setText(String.valueOf(ghe.getCot()));
                return;
            }
        }
        TXTHANG.setText("");
        TXTCOT.setText("");
    }

    public void Nhanvien() {
        QuanLyNhanVien nvi = new QuanLyNhanVien();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        nvi.setVisible(true);
        this.dispose();
        return;

    }

    public void Ve() {
        QuanLyVe ve = new QuanLyVe();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        ve.setVisible(true);
        this.dispose();
        return;

    }

    public void Phong() {
        QuanLyPhong phong = new QuanLyPhong();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        phong.setVisible(true);
        this.dispose();
        return;

    }

    public void Thietbi() {
        QuanLyThietBi tbi = new QuanLyThietBi();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        tbi.setVisible(true);
        this.dispose();
        return;

    }

    public void Khachhang() {
        PhanAnhKH khachhang = new PhanAnhKH();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        khachhang.setVisible(true);
        this.dispose();
        return;

    }

    public void Phim() {
        QuanLyPhim phim = new QuanLyPhim();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        phim.setVisible(true);
        this.dispose();
        return;

    }
}
