/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agilee;

//import java.awt.BorderLayout;
import DAO.MoviesDAO;
import DAO.NhanVienDao;
import DAO.PhongDao;
import DAO.ThietBiDAO;
import java.awt.Color;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Movies;
import model.NhanVien;
import model.Phong;
import model.Thietbi;

//import java.awt.Color;
//import java.awt.Font;
//import javax.swing.JFrame;
//import javax.swing.JLabel;
//import javax.swing.JPanel;
//import javax.swing.JScrollPane;
//import javax.swing.JTable;
//import javax.swing.table.DefaultTableCellRenderer;
//import javax.swing.table.JTableHeader;
/**
 *
 * @author admin
 */
public class QuanLyThietBi extends javax.swing.JFrame {

    List<Thietbi> list = new ArrayList<>();
    ThietBiDAO tbDAO = new ThietBiDAO();
    List<Phong> listphong = new ArrayList<>();
    PhongDao pDAO = new PhongDao();

    /**
     * Creates new form Login
     */
    public QuanLyThietBi() {
        initComponents();
        setLocationRelativeTo(null);
        loadDataToTable();

//        JTable table;
//        setTitle("JTableHeader");
//          JTableHeader jTableHeader = jTable2.getTableHeader();          
//          
//        
//
//        setTitle("JTableHeader");
//        jTableHeader.setBackground(Color.ORANGE);
//        jTableHeader.setForeground(Color.BLACK); 
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVe = new javax.swing.JButton();
        btnPhong = new javax.swing.JButton();
        btnThietbi = new javax.swing.JButton();
        btnNhanvien = new javax.swing.JButton();
        btnKhachhang = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnPhim = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmatb = new javax.swing.JTextField();
        txtTentb = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThietBi = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtSDPhong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1085, 627));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        btnVe.setBackground(new java.awt.Color(0, 0, 0));
        btnVe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVe.setForeground(new java.awt.Color(255, 255, 255));
        btnVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/390134.png"))); // NOI18N
        btnVe.setText("VÉ");
        btnVe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVeMouseExited(evt);
            }
        });
        btnVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeActionPerformed(evt);
            }
        });

        btnPhong.setBackground(new java.awt.Color(0, 0, 0));
        btnPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/phong.png"))); // NOI18N
        btnPhong.setText("PHÒNG");
        btnPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPhongMouseExited(evt);
            }
        });
        btnPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongActionPerformed(evt);
            }
        });

        btnThietbi.setBackground(new java.awt.Color(0, 0, 0));
        btnThietbi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThietbi.setForeground(new java.awt.Color(255, 255, 255));
        btnThietbi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thietbi.png"))); // NOI18N
        btnThietbi.setText("THIẾT BỊ");
        btnThietbi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThietbiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThietbiMouseExited(evt);
            }
        });

        btnNhanvien.setBackground(new java.awt.Color(0, 0, 0));
        btnNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNhanvien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nhanvien.png"))); // NOI18N
        btnNhanvien.setText("NHÂN VIÊN");
        btnNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanvienMouseExited(evt);
            }
        });
        btnNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanvienActionPerformed(evt);
            }
        });

        btnKhachhang.setBackground(new java.awt.Color(0, 0, 0));
        btnKhachhang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKhachhang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/khach.png"))); // NOI18N
        btnKhachhang.setText("KHÁCH HÀNG");
        btnKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhachhangMouseExited(evt);
            }
        });
        btnKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachhangActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("QUẢN LÍ THIẾT BỊ");

        btnPhim.setBackground(new java.awt.Color(0, 0, 0));
        btnPhim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPhim.setForeground(new java.awt.Color(255, 255, 255));
        btnPhim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/a2.png"))); // NOI18N
        btnPhim.setText("PHIM");
        btnPhim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPhimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPhimMouseExited(evt);
            }
        });
        btnPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVe, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThietbi, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPhim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKhachhang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addComponent(btnPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnVe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnThietbi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Mã Thiết Bị");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("Tên Thiết Bị");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Mô Tả");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 90, -1));

        txtmatb.setBackground(new java.awt.Color(0, 153, 0));
        txtmatb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtmatb.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtmatb, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 280, 30));

        txtTentb.setBackground(new java.awt.Color(0, 153, 0));
        txtTentb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTentb.setForeground(new java.awt.Color(255, 255, 255));
        txtTentb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTentbActionPerformed(evt);
            }
        });
        getContentPane().add(txtTentb, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 280, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Cre: Dr. Stone");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 600, 80, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 204, 255));
        jLabel12.setText("Tên Tài Khoản: user1");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 150, -1));

        btnAdd.setBackground(new java.awt.Color(153, 153, 255));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 120, 40));

        btnUpdate.setBackground(new java.awt.Color(153, 153, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 150, 120, 40));

        btnDelete.setBackground(new java.awt.Color(153, 153, 255));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 120, 40));

        tblThietBi.setBackground(new java.awt.Color(255, 51, 255));
        tblThietBi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Thiết Bị ", "Tên Thiết Bị", "Số Lượng", "Sử Dụng Tại Phòng"
            }
        ));
        tblThietBi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThietBiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblThietBi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 840, 290));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Sử dụng tại phòng");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        txtSDPhong.setBackground(new java.awt.Color(0, 153, 0));
        txtSDPhong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSDPhong.setForeground(new java.awt.Color(255, 255, 255));
        txtSDPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDPhongActionPerformed(evt);
            }
        });
        getContentPane().add(txtSDPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 280, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setText("Số Lượng");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 90, -1));

        txtSoLuong.setBackground(new java.awt.Color(0, 153, 0));
        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSoLuong.setForeground(new java.awt.Color(255, 255, 255));
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });
        getContentPane().add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 280, 30));

        txtMota.setBackground(new java.awt.Color(0, 153, 0));
        txtMota.setColumns(20);
        txtMota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMota.setForeground(new java.awt.Color(255, 255, 255));
        txtMota.setRows(5);
        jScrollPane2.setViewportView(txtMota);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 280, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/—Pngtree—geometric purple background with modern_1243070.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1070, 620));

        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTentbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTentbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTentbActionPerformed

    private void btnNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanvienActionPerformed
        Nhanvien();
    }//GEN-LAST:event_btnNhanvienActionPerformed

    public void setColor(JButton p) {
        p.setBackground(new Color(204, 255, 204));
        p.setForeground(new Color(0, 0, 0));
    }

    public void resetColor(JButton p) {
        p.setBackground(new Color(0, 0, 0));
        p.setForeground(new Color(255, 255, 255));
    }

    public void setColor1(JButton p) {
        p.setBackground(new Color(255, 153, 0));
        p.setForeground(new Color(255, 255, 255));
    }

    public void resetColor1(JButton p) {
        p.setBackground(new Color(153, 153, 225));
        p.setForeground(new Color(0, 0, 0));
    }


    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here: 
    }//GEN-LAST:event_jPanel1MouseEntered

    private void btnPhimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhimMouseExited
        // TODO add your handling code here:
        resetColor(btnPhim);
    }//GEN-LAST:event_btnPhimMouseExited

    private void btnPhimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhimMouseEntered
        // TODO add your handling code here:
        setColor(btnPhim);
    }//GEN-LAST:event_btnPhimMouseEntered

    private void btnVeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeMouseEntered
        // TODO add your handling code here:
        setColor(btnVe);
    }//GEN-LAST:event_btnVeMouseEntered

    private void btnVeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeMouseExited
        // TODO add your handling code here:
        resetColor(btnVe);
    }//GEN-LAST:event_btnVeMouseExited

    private void btnPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseEntered
        // TODO add your handling code here:
        setColor(btnPhong);
    }//GEN-LAST:event_btnPhongMouseEntered

    private void btnPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongMouseExited
        // TODO add your handling code here:
        resetColor(btnPhong);
    }//GEN-LAST:event_btnPhongMouseExited

    private void btnThietbiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThietbiMouseEntered
        // TODO add your handling code here:
        setColor(btnThietbi);
    }//GEN-LAST:event_btnThietbiMouseEntered

    private void btnThietbiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThietbiMouseExited
        // TODO add your handling code here:
        resetColor(btnThietbi);
    }//GEN-LAST:event_btnThietbiMouseExited

    private void btnNhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanvienMouseEntered
        // TODO add your handling code here:
        setColor(btnNhanvien);
    }//GEN-LAST:event_btnNhanvienMouseEntered

    private void btnNhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanvienMouseExited
        // TODO add your handling code here:
        resetColor(btnNhanvien);
    }//GEN-LAST:event_btnNhanvienMouseExited

    private void btnKhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachhangMouseEntered
        // TODO add your handling code here:
        setColor(btnKhachhang);
    }//GEN-LAST:event_btnKhachhangMouseEntered

    private void btnKhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachhangMouseExited
        // TODO add your handling code here:
        resetColor(btnKhachhang);
    }//GEN-LAST:event_btnKhachhangMouseExited

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        UpdateTB();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       xoaTB();

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        // TODO add your handling code here:
        setColor1(btnAdd);
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        // TODO add your handling code here:
        resetColor1(btnAdd);
    }//GEN-LAST:event_btnAddMouseExited

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        // TODO add your handling code here:
        setColor1(btnUpdate);
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        // TODO add your handling code here:
        resetColor1(btnUpdate);
    }//GEN-LAST:event_btnUpdateMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        // TODO add your handling code here:
        setColor1(btnDelete);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        // TODO add your handling code here:
        resetColor1(btnDelete);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhimActionPerformed
        Phim();
    }//GEN-LAST:event_btnPhimActionPerformed

    private void btnVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeActionPerformed
        Ve();
    }//GEN-LAST:event_btnVeActionPerformed

    private void btnPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongActionPerformed
        Phong();
    }//GEN-LAST:event_btnPhongActionPerformed

    private void btnKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachhangActionPerformed
        Khachhang();
    }//GEN-LAST:event_btnKhachhangActionPerformed

    private void txtSDPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDPhongActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addtb();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblThietBiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThietBiMouseClicked
        fillToFrom();
    }//GEN-LAST:event_tblThietBiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyThietBi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKhachhang;
    private javax.swing.JButton btnNhanvien;
    private javax.swing.JButton btnPhim;
    private javax.swing.JButton btnPhong;
    private javax.swing.JButton btnThietbi;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblThietBi;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtSDPhong;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTentb;
    private javax.swing.JTextField txtmatb;
    // End of variables declaration//GEN-END:variables
   public void loadDataToTable() {
        list = ThietBiDAO.getAll();
        listphong = PhongDao.getAll();
        String[] columnNames = {"Mã", "Tên ", "Số Lượng", "Mô Tả", "Sử Dụng Tại Phòng"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        for (Thietbi tb : list) {
            model.addRow(new Object[]{tb.getMatb(), tb.getTentb(), tb.getSoluongtb(), tb.getMotatb(), tb.getMaphong()});
        }
        tblThietBi.setModel(model);
    }

    public void fillToFrom() {
        int index = tblThietBi.getSelectedRow();
        Thietbi thietbi = list.get(index);
        txtmatb.setText(thietbi.getMatb());
        txtTentb.setText(thietbi.getTentb());
        txtSoLuong.setText(String.valueOf(thietbi.getSoluongtb()));
        txtMota.setText(thietbi.getMotatb());
        txtSDPhong.setText(thietbi.getMaphong());
    }

    public boolean checkfrom() {
        if (txtmatb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã thiết bị");
            return false;
        }
        if (checkmatb() == false) {
            return false;
        }
        if (txtTentb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên thiết bị");
            return false;
        }
        if (txtSoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập số lượng thiết bị");
            return false;
        }
        try {
            int sl = Integer.parseInt(txtSoLuong.getText());
            if (sl < 1) {
                JOptionPane.showMessageDialog(null, "Số lượng không được nhỏ hơn một");
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Số lượng phải là số");
            return false;
        }
        if (txtMota.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mô tả thiết bị");
            return false;
        }
        if (txtSDPhong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa mã phòng đặt thiết bị");
            return false;
        }
        if (checkMap() == false) {
            return false;
        }
        return true;
    }

    public boolean checkfromUPDATE() {
        if (txtmatb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã thiết bị");
            return false;
        }
        if (checkmatb2() == false) {
            return false;
        }
        if (txtTentb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tên thiết bị");
            return false;
        }
        if (txtSoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập số lượng thiết bị");
            return false;
        }
        try {
            int sl = Integer.parseInt(txtSoLuong.getText());
            if (sl < 1) {
                JOptionPane.showMessageDialog(null, "Số lượng không được nhỏ hơn một");
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Số lượng phải là số");
            return false;
        }
        if (txtMota.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mô tả thiết bị");
            return false;
        }
        if (txtSDPhong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã phòng đặt thiết bị");
            return false;
        }
        if (checkMap() == false) {
            return false;
        }
        return true;
    }

    public boolean checkmatb() {
        for (Thietbi thietbi : list) {
            if (txtmatb.getText().equals(thietbi.getMatb())) {
                JOptionPane.showMessageDialog(null, "Thiết bị đã có trong danh sách");
                return false;
            }
        }
        return true;
    }

    public boolean checkmatb2() {
        for (Thietbi thietbi : list) {
            if (txtmatb.getText().equals(thietbi.getMatb())) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(null, "Không tìm thấy mã thiết bị để tiến hành update");
        return false;
    }

    public boolean checkmatb3() {
        for (Thietbi thietbi : list) {
            if (txtmatb.getText().equals(thietbi.getMatb())) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(null, "Không tìm thấy mã thiết bị để tiến hành xóa");
        return false;
    }

    public boolean checkMap() {
        for (Phong phong : listphong) {
            if (txtSDPhong.getText().equals(phong.getMa())) {
                return true;
            }
        }
        JOptionPane.showMessageDialog(null, "Phòng không tồn tại");
        return false;
    }

    public void addtb() {
        if (checkfrom()) {
            Thietbi thietbi = new Thietbi();
            thietbi.setMatb(txtmatb.getText());
            thietbi.setTentb(txtTentb.getText());
            thietbi.setSoluongtb(Integer.parseInt(txtSoLuong.getText()));
            thietbi.setMotatb(txtMota.getText());
            thietbi.setMaphong(txtSDPhong.getText());
            int rs = ThietBiDAO.insert(thietbi);
            loadDataToTable();
            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công");

            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại");
            }
        }
    }

    public void UpdateTB() {
        if (checkfromUPDATE()) {
            for (Thietbi thietbi : list) {
                if (txtmatb.getText().equals(thietbi.getMatb())) {
                    thietbi.setMatb(txtmatb.getText());
                    thietbi.setTentb(txtTentb.getText());
                    thietbi.setSoluongtb(Integer.parseInt(txtSoLuong.getText()));
                    thietbi.setMotatb(txtMota.getText());
                    thietbi.setMaphong(txtSDPhong.getText());
                    int rs = ThietBiDAO.update(thietbi);
                    loadDataToTable();
                    if (rs > 0) {
                        JOptionPane.showMessageDialog(null, "Thêm thành công");

                    } else {
                        JOptionPane.showMessageDialog(null, "Thêm thất bại");
                    }
                }
            }

        }
    }

    public void newfrom() {
        txtmatb.setText("");
        txtTentb.setText("");
        txtSoLuong.setText("");
        txtMota.setText("");
        txtSDPhong.setText("");
    }

    public void xoaTB() {
        String ma = txtmatb.getText();
        if (txtmatb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã thiết bị");
            return;
        }
        if (checkmatb3()) {
            for (Thietbi thietbi : list) {
                if (ma.equals(thietbi.getMatb())) {
                    int rs = ThietBiDAO.delet(thietbi);
                    loadDataToTable();
                    newfrom();
                    if (rs > 0) {
                        JOptionPane.showMessageDialog(null, "Xóa thành công");

                    } else {
                        JOptionPane.showMessageDialog(null, "Xóa thất bại");
                    }
                    break;
                }
            }
        }

    }

    public void Nhanvien() {
        QuanLyNhanVien nvi = new QuanLyNhanVien();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        nvi.setVisible(true);
        this.dispose();
        return;

    }

    public void Ve() {
        QuanLyVe ve = new QuanLyVe();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        ve.setVisible(true);
        this.dispose();
        return;

    }

    public void Phong() {
        QuanLyPhong phong = new QuanLyPhong();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        phong.setVisible(true);
        this.dispose();
        return;

    }

    public void Thietbi() {
        QuanLyThietBi tbi = new QuanLyThietBi();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        tbi.setVisible(true);
        this.dispose();
        return;

    }

    public void Khachhang() {
        PhanAnhKH khachhang = new PhanAnhKH();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        khachhang.setVisible(true);
        this.dispose();
        return;

    }

    public void Phim() {
        QuanLyPhim phim = new QuanLyPhim();
//                JOptionPane.showMessageDialog(null, "Login succesfully");
        phim.setVisible(true);
        this.dispose();
        return;

    }

}
